receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
        max_recv_msg_size_mib: 4
      http:
        endpoint: 127.0.0.1:4318
        max_request_body_size: 4194304

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 768
    spike_limit_mib: 192
  batch:
    send_batch_size: 512
    send_batch_max_size: 1024
    timeout: 5s

exporters:
  nop: {}

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8888
                without_type_suffix: true
                without_units: true
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
