[Journal]
Storage=persistent
Compress=yes
Seal=yes
SystemMaxUse=2G
SystemKeepFree=10G
SystemMaxFileSize=256M
MaxFileSec=1day
MaxRetentionSec=7day
RateLimitIntervalSec=30s
RateLimitBurst=10000
ForwardToSyslog=no
