[Unit]
Requires=liqi-database-credentials.service
After=liqi-database-credentials.service

[Service]
Slice=liqi-database.slice
CPUQuota=20%
MemoryHigh=768M
MemoryMax=1G
MemorySwapMax=0
TasksMax=512
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/run/pgbouncer /var/log/pgbouncer
