[Unit]
Requires=liqi-secrets.service
After=liqi-secrets.service network-online.target

[Service]
Slice=liqi-database.slice
CPUQuota=80%
MemoryHigh=6G
MemoryMax=7G
MemorySwapMax=0
TasksMax=1536
OOMPolicy=stop
